/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as LogoutImport } from "./routes/logout";
import { Route as LoginImport } from "./routes/login";
import { Route as AuthedImport } from "./routes/_authed";
import { Route as AuthedIndexImport } from "./routes/_authed/index";
import { Route as AuthedPostsPostIdImport } from "./routes/_authed/posts.$postId";

// Create/Update Routes

const LogoutRoute = LogoutImport.update({
  id: "/logout",
  path: "/logout",
  getParentRoute: () => rootRoute,
} as any);

const LoginRoute = LoginImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRoute,
} as any);

const AuthedRoute = AuthedImport.update({
  id: "/_authed",
  getParentRoute: () => rootRoute,
} as any);

const AuthedIndexRoute = AuthedIndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthedRoute,
} as any);

const AuthedPostsPostIdRoute = AuthedPostsPostIdImport.update({
  id: "/posts/$postId",
  path: "/posts/$postId",
  getParentRoute: () => AuthedRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_authed": {
      id: "/_authed";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof AuthedImport;
      parentRoute: typeof rootRoute;
    };
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginImport;
      parentRoute: typeof rootRoute;
    };
    "/logout": {
      id: "/logout";
      path: "/logout";
      fullPath: "/logout";
      preLoaderRoute: typeof LogoutImport;
      parentRoute: typeof rootRoute;
    };
    "/_authed/": {
      id: "/_authed/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof AuthedIndexImport;
      parentRoute: typeof AuthedImport;
    };
    "/_authed/posts/$postId": {
      id: "/_authed/posts/$postId";
      path: "/posts/$postId";
      fullPath: "/posts/$postId";
      preLoaderRoute: typeof AuthedPostsPostIdImport;
      parentRoute: typeof AuthedImport;
    };
  }
}

// Create and export the route tree

interface AuthedRouteChildren {
  AuthedIndexRoute: typeof AuthedIndexRoute;
  AuthedPostsPostIdRoute: typeof AuthedPostsPostIdRoute;
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedPostsPostIdRoute: AuthedPostsPostIdRoute,
};

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren);

export interface FileRoutesByFullPath {
  "": typeof AuthedRouteWithChildren;
  "/login": typeof LoginRoute;
  "/logout": typeof LogoutRoute;
  "/": typeof AuthedIndexRoute;
  "/posts/$postId": typeof AuthedPostsPostIdRoute;
}

export interface FileRoutesByTo {
  "/login": typeof LoginRoute;
  "/logout": typeof LogoutRoute;
  "/": typeof AuthedIndexRoute;
  "/posts/$postId": typeof AuthedPostsPostIdRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/_authed": typeof AuthedRouteWithChildren;
  "/login": typeof LoginRoute;
  "/logout": typeof LogoutRoute;
  "/_authed/": typeof AuthedIndexRoute;
  "/_authed/posts/$postId": typeof AuthedPostsPostIdRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "" | "/login" | "/logout" | "/" | "/posts/$postId";
  fileRoutesByTo: FileRoutesByTo;
  to: "/login" | "/logout" | "/" | "/posts/$postId";
  id:
    | "__root__"
    | "/_authed"
    | "/login"
    | "/logout"
    | "/_authed/"
    | "/_authed/posts/$postId";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren;
  LoginRoute: typeof LoginRoute;
  LogoutRoute: typeof LogoutRoute;
}

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authed",
        "/login",
        "/logout"
      ]
    },
    "/_authed": {
      "filePath": "_authed.tsx",
      "children": [
        "/_authed/",
        "/_authed/posts/$postId"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/logout": {
      "filePath": "logout.tsx"
    },
    "/_authed/": {
      "filePath": "_authed/index.tsx",
      "parent": "/_authed"
    },
    "/_authed/posts/$postId": {
      "filePath": "_authed/posts.$postId.tsx",
      "parent": "/_authed"
    }
  }
}
ROUTE_MANIFEST_END */
